[project]
name = "neural-architecture-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.10"
dependencies = [
    "naslib",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
naslib = { path = "NASLib", editable = true }

[tool.uv.extra-build-dependencies]
grakel = ["pip", "numpy"]
